Repository robocorp/rpaframework, pull requests merged in 2021-11, with the labels that each got.

#274 windows: fix screenshot filename handling
  packages/main/src/RPA/Desktop/Windows.py
Labels: bug

#277 `Parse Work Item From Email` keyword for dict body
  docs/source/releasenotes.rst
  packages/main/src/RPA/Email/ImapSmtp.py
  packages/main/src/RPA/Robocorp/WorkItems.py
  packages/main/tests/python/test_robocorp_workitems.py
  packages/main/tests/resources/items.json
  packages/main/tests/resources/work-items/email-mika-no-json.txt
  packages/main/tests/resources/work-items/email-mika.txt
  packages/main/tests/robot/test_robocorp_workitems.robot
Labels: feature

#272 Release mail parsing keyword
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
Labels: documentation, packaging

#288 Fix PDF document active content and XML dumping
  packages/pdf/Makefile
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/__init__.py
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/src/RPA/PDF/keywords/finder.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/__init__.py
  packages/pdf/tests/python/test_document.py
  packages/pdf/tests/python/test_model.py
  packages/pdf/tests/robot/test.resource
  packages/pdf/tests/robot/test_pdf.robot
Labels: bug, enhancement, refactor

#289 imapsmtp: fix attachment filename and sender name encoding issues
  packages/main/src/RPA/Email/ImapSmtp.py
Labels: bug

#293 imapsmtp: fix handling of octet stream attachments
  packages/main/src/RPA/Email/ImapSmtp.py
Labels: bug

#285 Support JSON/YAML/Text input e-mail body content as work item
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/src/RPA/Robocorp/WorkItems.py
  packages/main/tests/python/test_robocorp_workitems.py
  packages/main/tests/resources/work-items/items.json
  packages/main/tests/resources/work-items/mail-json.txt
  packages/main/tests/resources/work-items/mail-text.txt
  packages/main/tests/resources/work-items/mail-yaml.txt
  packages/main/tests/robot/test_robocorp_workitems.robot
Labels: enhancement

#296 Keyword for converting e-mails into documents
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/ImapSmtp.py
  packages/main/tests/python/test_imapsmtp.py
  packages/main/tests/resources/emails/work-item-documentation.eml
  packages/main/tests/robot/test_email.robot
  packages/main/tests/robot/test_robocorp_vault.robot
Labels: feature, enhancement

#299 API retrier improvements on Work Items
  docs/source/releasenotes.rst
  packages/main/Makefile
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Robocorp/WorkItems.py
  packages/main/src/RPA/Robocorp/utils.py
  packages/main/tests/python/pytest.ini
  packages/main/tests/python/test_robocorp_workitems.py
Labels: enhancement

#300 PDF improvements on `Find Text` (breaking changes)
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/__init__.py
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/src/RPA/PDF/keywords/finder.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/test_document.py
  packages/pdf/tests/python/test_finder.py
  packages/pdf/tests/python/test_model.py
  packages/pdf/tests/resources/18467.pdf
  packages/pdf/tests/robot/test.resource
  packages/pdf/tests/robot/test_pdf.robot
Labels: enhancement, refactor
