Repository robocorp/rpaframework, pull requests merged in 2021-12, with the labels that each got.

#307 RPA.PDF: Post-merge fixes and docs
  .gitignore
  packages/pdf/.gitignore
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/__init__.py
  packages/pdf/src/RPA/PDF/assets/Inter-Regular.ttf
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/src/RPA/PDF/keywords/finder.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/__init__.py
  packages/pdf/tests/python/test_document.py
  packages/pdf/tests/python/test_model.py
  packages/pdf/tests/resources/foersom.pdf
  packages/pdf/tests/robot/test.resource
  packages/pdf/tests/robot/test_pdf.robot
Labels: documentation

#313 Add missing fonts for unicode PDFs
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/assets/Inter-Bold.ttf
  packages/pdf/src/RPA/PDF/assets/Inter-BoldItalic.ttf
  packages/pdf/src/RPA/PDF/assets/Inter-Italic.ttf
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/tests/python/test_document.py
Labels: bug

#314 Release 12.1.0 (PDF unicode fixes)
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
Labels: packaging

#315 Serialize PDF fonts in Robocorp home directory
  .github/workflows/pdf.yaml
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/document.py
Labels: enhancement

#316 Release 12.1.1 (PDF hotfix)
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
Labels: packaging

#322 Cleanup PDF serialized fonts with invalid paths
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/tests/python/test_document.py
Labels: bug

#331 Replace Makefile by Invoke
  packages/pdf/.gitignore
  packages/pdf/Makefile
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/tasks.py
Labels: packaging

#332 Release 12.1.2
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
Labels: packaging

#339 Fix bug when adding a watermark into the same PDF
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/__init__.py
  packages/pdf/tests/python/test_document.py
  packages/pdf/tests/resources/receipt.pdf
  packages/pdf/tests/resources/robot.png
  packages/pdf/tests/robot/test.resource
  packages/pdf/tests/robot/test_pdf.robot
Labels: bug

#340 Add migration guide on >=11 library update
  docs/source/releasenotes.rst
Labels: documentation

#335 Fix `RPA.Database.Query` (returning and transactions)
  docs/source/releasenotes.rst
  packages/main/src/RPA/Database.py
  packages/main/tests/python/__init__.py
  packages/main/tests/python/test_database.py
  packages/main/tests/resources/script.sql
  packages/main/tests/robot/test_database.robot
Labels: bug, enhancement

#342 Release 12.2.0
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: packaging

#345 Feature/google share
  .github/workflows/google.yaml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/google/src/RPA/Cloud/Google/keywords/drive.py
  packages/google/src/RPA/Cloud/Google/keywords/enums.py
  packages/google/tests/robot/test_drive.robot
  poetry.lock
Labels: enhancement
