Repository robocorp/rpaframework, pull requests merged in 2022-08, with the labels that each got.

#373 Support for locators path configuration
  docs/source/releasenotes.rst
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/locators/database.py
  packages/core/src/RPA/core/locators/literal.py
  packages/core/src/RPA/core/locators/syntax.py
  packages/core/tests/__init__.py
  packages/core/tests/resources/locators.json
  packages/core/tests/test_locators.py
  packages/core/tests/test_syntax.py
Labels: feature, refactor

#592 Optionally customize the `locators_path` with `RPA.Desktop`
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Desktop/__init__.py
  packages/main/src/RPA/Desktop/keywords/context.py
  packages/main/src/RPA/Desktop/keywords/finder.py
  poetry.lock
Labels: feature

#595 Fix bug with empty Salesforce result table
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Salesforce.py
  poetry.lock
Labels: bug

#597 `Get File Stem` keyword under `RPA.FileSystem` library
  docs/source/releasenotes.rst
  packages/main/src/RPA/FileSystem.py
  packages/main/tests/robot/test_files.robot
Labels: feature

#495 `RPA.Tables`: Add keywords for mapping column values and removing rows with custom filters
  docs/source/releasenotes.rst
  packages/main/src/RPA/Excel/Files.py
  packages/main/src/RPA/Tables.py
  packages/main/tests/robot/test_tables.robot
Labels: feature

#600 Bump `lxml` dep to 4.9.1
  docs/source/releasenotes.rst
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/dialogs/poetry.lock
  packages/dialogs/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
  packages/recognition/src/RPA/recognition/templates.py
Labels: dependency

#599 Handle formatted cells as empty when appending
  docs/source/releasenotes.rst
  packages/main/src/RPA/Excel/Files.py
  packages/main/tests/resources/excels/data1.xls
  packages/main/tests/resources/excels/data1.xlsx
  packages/main/tests/resources/excels/data2.xls
  packages/main/tests/resources/excels/data2.xlsx
  packages/main/tests/resources/excels/data_template.xls
  packages/main/tests/resources/excels/data_template.xlsx
  packages/main/tests/robot/test_excel.robot
Labels: enhancement

#603 notifier: fix how keyword parameters are forwarded
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Notifier.py
Labels: bug

#605 RPA.Database: add support for new ``oracledb`` connector
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/src/RPA/Database.py
Labels: enhancement

#606 Use `webdriver-manager` with `core` for Selenium 4
  packages/core/Makefile
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/webdriver.py
  packages/core/tests/test_webdriver.py
Labels: enhancement, breaking

#612 Latest core in all subpackages (v10.0.0)
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/dialogs/poetry.lock
  packages/dialogs/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/main/pyproject.toml
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
Labels: packaging, dependency

#611 Add new keywords to `Robocorp.Process` library
  docs/source/releasenotes.rst
  packages/main/src/RPA/Robocorp/Process.py
Labels: enhancement

#610 New library `RPA.MFA`
  docs/source/libraries/mfa/index.rst
  docs/source/libraries/mfa/python.rst
  docs/source/releasenotes.rst
  packages/main/README.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/MFA.py
Labels: feature

#602 Upgrade to Selenium 4
  docs/source/releasenotes.rst
  packages/main/.gitignore
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/tests/robot/test_browser.robot
  poetry.lock
  pyproject.toml
Labels: enhancement
