Repository robocorp/rpaframework, pull requests merged in 2022-03, with the labels that each got.

#402 `RPA.Windows` generic fixes (recording, refactors/restructure, latest core)
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/keywords/action.py
  packages/windows/src/RPA/Windows/keywords/context.py
  packages/windows/src/RPA/Windows/keywords/elements.py
  packages/windows/src/RPA/Windows/keywords/locators.py
  packages/windows/src/RPA/Windows/keywords/window.py
  packages/windows/src/RPA/Windows/main.py
  packages/windows/src/RPA/Windows/utils.py
  poetry.lock
Labels: enhancement

#401 Option to windows list_windows to save icons to file
  packages/core/pyproject.toml
  packages/core/src/RPA/core/windows/window.py
Labels: bug

#407 `RPA.Desktop`: Type annotations
  packages/main/src/RPA/Desktop/keywords/application.py
Labels: documentation

#414 selenium. on auto_close False Windows, kill driver's chromedriver pro…
  packages/main/src/RPA/Browser/Selenium.py
Labels: bug

#419 robocorp.process: add keyword list_process_run_work_items
  packages/main/src/RPA/Robocorp/Process.py
Labels: enhancement

#416 Email bug fixes and enhancements
  packages/main/poetry.lock
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/src/RPA/Email/Exchange.py
  packages/main/src/RPA/Email/ImapSmtp.py
  packages/main/src/RPA/Robocorp/Process.py
  packages/main/tests/python/test_exchange.py
Labels: bug

#421 docs. development guide
  packages/main/README.rst
  poetry.lock
Labels: documentation

#430 Fix/http library less logging
  packages/main/README.rst
  packages/main/src/RPA/HTTP.py
  packages/main/src/RPA/Robocorp/Process.py
  poetry.lock
Labels: enhancement

#425 Align core with windows (& packaging chores)
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/vendor/__init__.py
  packages/core/src/RPA/core/vendor/robotlibcore.py
  packages/core/src/RPA/core/windows/__init__.py
  packages/core/src/RPA/core/windows/context.py
  packages/core/src/RPA/core/windows/helpers.py
  packages/core/src/RPA/core/windows/inspect.py
  packages/core/src/RPA/core/windows/locators.py
  packages/core/src/RPA/core/windows/window.py
  poetry.lock
  pyproject.toml
Labels: packaging, enhancement, refactor, p-high

#432 Base `windows` on latest `core`
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/__init__.py
  packages/windows/src/RPA/Windows/keywords/action.py
  packages/windows/src/RPA/Windows/keywords/context.py
  packages/windows/src/RPA/Windows/keywords/elements.py
  packages/windows/src/RPA/Windows/keywords/locators.py
  packages/windows/src/RPA/Windows/keywords/window.py
  packages/windows/src/RPA/Windows/main.py
  packages/windows/src/RPA/Windows/utils.py
Labels: enhancement, refactor

#434 recognition: core 7.0.0
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
Labels: packaging

#435 Base `windows` on latest `core`
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/__init__.py
  packages/windows/src/RPA/Windows/keywords/action.py
  packages/windows/src/RPA/Windows/keywords/context.py
  packages/windows/src/RPA/Windows/keywords/elements.py
  packages/windows/src/RPA/Windows/keywords/locators.py
  packages/windows/src/RPA/Windows/keywords/window.py
  packages/windows/src/RPA/Windows/main.py
  packages/windows/src/RPA/Windows/utils.py
  packages/windows/tests/robot/test_windows.robot
Labels: bug, enhancement, refactor

#431 Release/12.10.0
  docs/source/releasenotes.rst
  packages/main/README.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Cloud/AWS.py
  packages/main/src/RPA/Desktop/Windows.py
  packages/main/src/RPA/HTTP.py
  poetry.lock
  pyproject.toml
Labels: bug, packaging, refactor

#433 Bump every package to core 7.0.0
  .github/workflows/dialogs.yaml
  .github/workflows/google.yaml
  .github/workflows/main.yaml
  .github/workflows/pdf.yaml
  .github/workflows/recognition.yaml
  .github/workflows/windows.yaml
  packages/dialogs/poetry.lock
  packages/dialogs/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/recognition/pyproject.toml
  packages/windows/pyproject.toml
Labels: packaging

#440 Register marked "keyword" methods
  packages/core/Makefile
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/locators/database.py
  packages/core/src/RPA/core/vendor/deco.py
  packages/core/src/RPA/core/vendor/robotlibcore.py
  packages/core/src/RPA/core/windows/locators.py
  packages/core/src/RPA/core/windows/window.py
Labels: bug

#437 Release `main` 13.0.0
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: packaging
