Repository robocorp/rpaframework, pull requests merged in 2022-09, with the labels that each got.

#616 Support custom `port` with Selenium
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/tests/robot/test_browser.robot
  poetry.lock
Labels: feature

#617 Fix Windows bug when clicking retrieved elements
  docs/source/releasenotes.rst
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/keywords/locators.py
  packages/windows/tests/robot/test_windows.robot
Labels: bug

#622 `RPA.Email.ImapSmtp`: Add possibility to position attachments within email content
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/ImapSmtp.py
  poetry.lock
Labels: enhancement

#623 Human-friendly options in Selenium
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/tests/python/test_browser.py
  packages/main/tests/robot/test_browser.robot
  poetry.lock
Labels: enhancement

#619 Google. Add support for Document AI API
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/google/src/RPA/Cloud/Google/__init__.py
  packages/google/src/RPA/Cloud/Google/keywords/__init__.py
  packages/google/src/RPA/Cloud/Google/keywords/base.py
  packages/google/src/RPA/Cloud/Google/keywords/context.py
  packages/google/src/RPA/Cloud/Google/keywords/document_ai.py
Labels: enhancement

#637 Add possibility to define additional parameters for S3 keywords
  .github/workflows/aws.yaml
  docs/source/releasenotes.rst
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/aws/src/RPA/Cloud/AWS/__init__.py
  packages/aws/tests/robot/test_cloud_aws.robot
Labels: documentation, enhancement, breaking

#639 Add new IDP libraries for Base64 and Nanonets services
  docs/source/libraries/base64ai/index.rst
  docs/source/libraries/base64ai/python.rst
  docs/source/libraries/nanonets/index.rst
  docs/source/libraries/nanonets/python.rst
  docs/source/releasenotes.rst
  packages/main/README.rst
  packages/main/poetry.lock
  packages/main/src/RPA/Base64AI.py
  packages/main/src/RPA/Nanonets.py
Labels: feature

#642 Use Vault for OAuth2 token auto-refresh in `RPA.Email.Exchange`
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/Exchange.py
  poetry.lock
Labels: enhancement

#643 Fix `access_type` param usage with Authorize
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/Exchange.py
  poetry.lock
Labels: enhancement

#644 Set flag `--yes-to-all` for publish action of packages to CI
  .github/workflows/aws.yaml
  .github/workflows/core.yaml
  .github/workflows/dialogs.yaml
  .github/workflows/google.yaml
  .github/workflows/main.yaml
  .github/workflows/pdf.yaml
  .github/workflows/recognition.yaml
  .github/workflows/windows.yaml
Labels: bug

#647 `RPA.Windows` - add keywords "Set Focus" and "Drag and Drop"
  docs/source/releasenotes.rst
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/keywords/action.py
  packages/windows/src/RPA/Windows/keywords/locators.py
Labels: feature

#648 `RPA.Cloud.AWS` - Add keyword "Generate Presigned URL"
  docs/source/releasenotes.rst
  packages/aws/pyproject.toml
  packages/aws/src/RPA/Cloud/AWS/__init__.py
Labels: feature
