Repository robocorp/rpaframework, pull requests merged in 2022-10, with the labels that each got.

#649 `RPA.Database` - Add support for all psycopg modules
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Database.py
Labels: enhancement

#652 Update lock files for meta and `rpaframework`
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: bug

#653 Add code from `rpaframework-msgraph` library challenge
  docs/source/libraries/msgraph/index.rst
  docs/source/libraries/msgraph/python.rst
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/MSGraph.py
  packages/main/tests/python/test_msgraph.py
  poetry.lock
Labels: feature

#660 Selenium `use_profile` enablement was skipped internally
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  poetry.lock
Labels: bug

#659 Add error when publishing to PyPI off `master` branch
  invocations/build.py
  invocations/errors.py
  invocations/shell.py
Labels: packaging, enhancement

#662 Patch the downloader for good Mac M1 URL
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/webdriver.py
Labels: bug

#665 Fix Selenium webdriver downloads on Mac arm64
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: bug

#666 `RPA.Outlook.Application` - add option to save as draft
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/src/RPA/Outlook/Application.py
  packages/main/tests/robot/test_outlook_application.robot
Labels: feature

#667 `RPA.Database` - add support for mysql ssl configuration
  docs/source/releasenotes.rst
  packages/main/src/RPA/Database.py
Labels: feature

#656 New keywords for the `RPA.SAP` library
  docs/source/releasenotes.rst
  packages/main/src/RPA/SAP.py
Labels: enhancement

#670 Fix bugs in listing files for Sharepoint (closes #669)
  docs/source/releasenotes.rst
  packages/main/pyproject.toml
  packages/main/src/RPA/MSGraph.py
  packages/main/tests/python/test_msgraph.py
Labels: bug

#664 Implement reStructured Text Linting on docstrings and docs
  invocations/analysis.py
  invocations/build.py
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/dialogs/poetry.lock
  packages/dialogs/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: packaging, enhancement

#650 `RPA.DocumentAI` Intelligent Document Processing generic keywords
  docs/source/releasenotes.rst
  packages/google/src/RPA/Cloud/Google/keywords/document_ai.py
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/DocumentAI/Base64AI.py
  packages/main/src/RPA/DocumentAI/DocumentAI.py
  packages/main/src/RPA/DocumentAI/Nanonets.py
  packages/main/src/RPA/DocumentAI/__init__.py
  packages/main/src/RPA/JSON.py
  packages/main/tests/python/test_documentai.py
  packages/main/tests/resources/secrets.yaml
  packages/main/tests/robot/test_documentai.robot
  poetry.lock
Labels: feature
