Repository robocorp/rpaframework, pull requests merged in 2022-04, with the labels that each got.

#448 aws: fix vault usage
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/aws/src/RPA/Cloud/AWS/__init__.py
Labels: bug

#450 imapsmtp. fix send message with cc and bcc
  packages/main/src/RPA/Email/ImapSmtp.py
Labels: bug

#449 `rpaframework` release 13.0.2
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/ImapSmtp.py
  poetry.lock
Labels: bug

#453 `RPA.Database`: Normalize rows to list of tuples
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Database.py
  poetry.lock
Labels: bug, enhancement

#456 Fix `RPA.Database` config getter
  docs/source/releasenotes.rst
  packages/main/src/RPA/Database.py
Labels: bug

#467 Support single quotes in windows locator names | More windows listing attributes
  docs/source/releasenotes.rst
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/windows/inspect.py
  packages/core/src/RPA/core/windows/locators.py
  packages/core/src/RPA/core/windows/window.py
  packages/core/tests/test_locators.py
  packages/core/tests/test_windows.py
Labels: bug, refactor, breaking

#471 Hotfix `core` windows locator sibling
  docs/source/releasenotes.rst
  packages/core/pyproject.toml
  packages/core/src/RPA/core/windows/locators.py
Labels: bug

#468 `RPA.Windows` 3.1.0
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/tests/robot/test_windows.robot
Labels: bug, enhancement, refactor

#472 Release `main` 13.3.0
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: packaging, dependencies

#473 Fix `RPA.Windows` docs & logging (+ refactor)
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/__init__.py
  packages/windows/src/RPA/Windows/keywords/action.py
  packages/windows/src/RPA/Windows/keywords/elements.py
  packages/windows/src/RPA/Windows/keywords/locators.py
  packages/windows/src/RPA/Windows/keywords/window.py
  packages/windows/tests/robot/test_windows.robot
Labels: documentation, refactor

#474 Release `main` 13.3.1
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
  pyproject.toml
Labels: documentation, packaging

#475 Remove .pkl deprecated font-serialization in PDF
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/tests/python/test_document.py
Labels: bug, packaging

#470 Add Robot Framework v5 support
  packages/aws/.gitignore
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/aws/tests/robot/test_cloud_aws.robot
  packages/dialogs/poetry.lock
  packages/dialogs/pyproject.toml
  packages/google/.gitignore
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/google/tests/robot/test_drive.robot
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/tests/robot/test_json.robot
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/tests/python/test_windows.py
  poetry.lock
  pyproject.toml
Labels: packaging, epic, upstream, dependency, breaking
