Repository robocorp/rpaframework, pull requests merged in 2022-06, with the labels that each got.

#534 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#536 Extend work item examples
  docs/source/releasenotes.rst
  packages/main/src/RPA/Robocorp/WorkItems.py
  poetry.lock
  pyproject.toml
Labels: documentation, dependency

#508 RPA.Cloud.AWS Create Redshift Data service and STS service
  docs/source/releasenotes.rst
  packages/aws/.gitignore
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/aws/src/RPA/Cloud/AWS/__init__.py
  packages/aws/tests/python/custom_redshiftdata/__init__.py
  packages/aws/tests/python/custom_redshiftdata/exceptions.py
  packages/aws/tests/python/custom_redshiftdata/models.py
  packages/aws/tests/python/custom_redshiftdata/responses.py
  packages/aws/tests/python/custom_redshiftdata/urls.py
  packages/aws/tests/python/test_redshift_data.py
  packages/aws/tests/robot/test_aws_redshift_data.robot
  packages/main/README.rst
  poetry.lock
  pyproject.toml
  tasks.py
Labels: feature

#541 Deprecate Lab references
  docs/source/contributing/conventions.rst
  docs/source/libraries/browser_playwright/index.rst
  docs/source/releasenotes.rst
  packages/main/src/RPA/Desktop/__init__.py
Labels: documentation

#550 Fix JSON infinite recursion on libspec with `JSONType`
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/JSON.py
  poetry.lock
Labels: bug

#492 RPA.Tables Examples Updated
  docs/source/releasenotes.rst
  packages/main/src/RPA/Tables.py
Labels: documentation

#493 RPA.Excel.Files typehint updates
  docs/source/releasenotes.rst
  packages/main/src/RPA/Excel/Files.py
Labels: documentation

#549 Create extended PDF examples
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/resources/sparebin-receipt.pdf
  packages/pdf/tests/robot/test_pdf.robot
Labels: documentation

#555 main: 15.1.2
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: packaging

#561 `RPA.Desktop` docs examples fix on `Region` element
  docs/source/releasenotes.rst
  packages/main/src/RPA/Desktop/keywords/finder.py
Labels: documentation

#562 Fix libspec source modifier
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/aws/tasks.py
  packages/dialogs/tasks.py
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/google/tasks.py
  packages/main/tasks.py
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/tasks.py
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/__init__.py
  packages/windows/tasks.py
  tasks.py
  tasks_common.py
Labels: packaging

#568 Add `RPA.FileSystem` examples and type hints
  docs/source/releasenotes.rst
  packages/main/src/RPA/FileSystem.py
Labels: documentation
