Repository robocorp/rpaframework, pull requests merged in 2022-07, with the labels that each got.

#569 `RPA.Email.Exchange` OAuth2 support
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/Exchange.py
  packages/main/tests/python/test_exchange.py
  poetry.lock
Labels: feature, p-high

#582 Fix macro running with odd Excel file names
  docs/source/releasenotes.rst
  packages/main/pyproject.toml
  packages/main/src/RPA/Excel/Application.py
  packages/main/tests/resources/excels/boldmacro-x.xlsm
  packages/main/tests/robot/test_excel_application.robot
  packages/main/tests/robot/test_word_application.robot
  poetry.lock
Labels: bug

#539 Work Items: Auto-release input work item on failure
  docs/source/releasenotes.rst
  packages/main/src/RPA/Robocorp/WorkItems.py
  packages/main/tests/python/test_robocorp_workitems.py
  packages/main/tests/robot/test_robocorp_workitems.robot
Labels: enhancement

#588 Fix offset computation on Windows mouse click
  .github/workflows/windows.yaml
  docs/source/releasenotes.rst
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/keywords/action.py
  packages/windows/tasks.py
  packages/windows/tests/python/test_windows.py
  packages/windows/tests/robot/test_windows.robot
Labels: bug

#590 `RPA.PDF`: Fix pages resolution logic
  docs/source/releasenotes.rst
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/context.py
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/test_document.py
Labels: bug, documentation
