Repository robocorp/rpaframework, pull requests merged in 2022-05, with the labels that each got.

#486 Fix the `Blocks` and `RPA.Tables` issues in the `RPA.Cloud.AWS` library
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/aws/src/RPA/Cloud/AWS/__init__.py
Labels: bug

#499 Add GMail support for OAuth2 flow
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/ImapSmtp.py
  packages/main/tests/python/test_imapsmtp.py
  packages/main/tests/resources/secrets.yaml
  packages/main/tests/robot/test_email.robot
  poetry.lock
Labels: enhancement

#511 Hubspot bug fix rollup
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/src/RPA/Hubspot.py
  poetry.lock
Labels: bug

#513 Update RPA.Vault documentation to link to docs and clarify
  packages/main/src/RPA/Robocorp/Vault.py
Labels: documentation

#509 Fix JSON deletion with filtering
  docs/source/releasenotes.rst
  packages/main/src/RPA/JSON.py
  packages/main/tests/python/test_json.py
  packages/main/tests/robot/test_json.robot
Labels: bug

#524 upgrade pillow package to 9.1.1
  packages/google/poetry.lock
  packages/google/pyproject.toml
Labels: dependency

#525 upgrade pillow package to 9.1.1
  packages/dialogs/poetry.lock
  packages/dialogs/pyproject.toml
Labels: dependency

#526 upgrade pillow package to 9.1.1
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
Labels: dependency

#527 upgrade pillow package to 9.1.1
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
Labels: dependency

#528 upgrade pillow package to 9.1.1
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
Labels: dependency

#529 upgrade pillow package to 9.1.1
  packages/main/poetry.lock
  packages/main/pyproject.toml
Labels: dependency
