Repository robocorp/rpaframework, pull requests merged in 2022-11, with the labels that each got.

#684 `RPA.Cloud.AWS`: Fix ``List Files`` on empty response
  docs/source/releasenotes.rst
  packages/aws/src/RPA/Cloud/AWS/__init__.py
Labels: bug

#685 `RPA.HTTP` - Add `Check Vulnerabilities` keyword
  docs/source/releasenotes.rst
  packages/main/src/RPA/HTTP.py
Labels: feature

#687 Reorder imports so `win32api` is imported before `pywintypes`
  packages/main/pyproject.toml
  packages/main/src/RPA/Outlook/Application.py
Labels: bug

#691 Fix `DocumentAI` docs
  docs/source/libraries/base64ai/index.rst
  docs/source/libraries/documentai/index.rst
  docs/source/libraries/documentai/python.rst
  docs/source/libraries/documentai_base64ai/index.rst
  docs/source/libraries/documentai_base64ai/python.rst
  docs/source/libraries/documentai_nanonets/index.rst
  docs/source/libraries/documentai_nanonets/python.rst
  docs/source/libraries/nanonets/index.rst
  packages/main/README.rst
  packages/main/poetry.lock
  poetry.lock
Labels: bug, documentation

#692 Allow email input Work Item var without trigger
  docs/source/releasenotes.rst
  packages/main/src/RPA/Robocorp/WorkItems.py
  packages/main/src/RPA/Robocorp/utils.py
  packages/main/tests/python/test_robocorp_workitems.py
Labels: bug

#679 Various `RPA.Windows` fixes
  packages/core/src/RPA/core/windows/locators.py
  packages/windows/src/RPA/Windows/keywords/action.py
Labels: bug, enhancement

#698 Fix core locators on finding similar elements
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/windows/locators.py
Labels: bug, refactor

#701 Better root element resolution
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/windows/locators.py
Labels: enhancement

#713 `RPA.Slack`. Add blocks property support for messages
  docs/source/releasenotes.rst
  packages/main/src/RPA/Slack.py
Labels: enhancement

#714 Fix Selenium `auto_close=${False}`
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: bug, dependency

#706 Introduce and use OAuth2 keywords from `RPA.MFA`
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/Exchange.py
  packages/main/src/RPA/Email/ImapSmtp.py
  packages/main/src/RPA/Email/common.py
  packages/main/src/RPA/MFA.py
  packages/main/src/RPA/Robocorp/utils.py
  poetry.lock
Labels: feature
