Repository robocorp/rpaframework, pull requests merged in 2023-05, with the labels that each got.

#936 Bump `cryptography` to 40.x.x
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: dependency

#930 Close RPA.Email.ImapSmtp Send Message should not require recipients #454
  docs/source/releasenotes.rst
  packages/main/src/RPA/Email/Exchange.py
  packages/main/src/RPA/Email/ImapSmtp.py
  packages/main/src/RPA/Email/common.py
  packages/main/tests/python/test_imapsmtp.py
Labels: bug

#944 `RPA.Database` Improvements for 'call stored procedure'
  docs/source/releasenotes.rst
  packages/main/src/RPA/Database.py
Labels: bug, enhancement

#945 `Excel/Outlook/Word.Application`. autoexit documentation and adding autoexit to word.application
  docs/source/releasenotes.rst
  packages/main/src/RPA/Excel/Application.py
  packages/main/src/RPA/Outlook/Application.py
  packages/main/src/RPA/Word/Application.py
Labels: documentation, enhancement

#948 `RPA.Email.*` reply and return path
  docs/source/releasenotes.rst
  packages/main/src/RPA/Email/Exchange.py
  packages/main/src/RPA/Email/ImapSmtp.py
  packages/main/tests/python/test_imapsmtp.py
Labels: enhancement

#943 Selenium epic 02 May 2023
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/tests/python/test_browser.py
  packages/main/tests/python/test_javaaccessbridge.py
  packages/main/tests/robot/test_browser.robot
  poetry.lock
Labels: epic

#971 Correct Chromium web-driver management
  docs/source/releasenotes.rst
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/webdriver.py
Labels: bug
