Repository robocorp/rpaframework, pull requests merged in 2023-06, with the labels that each got.

#974 Browser epic - 23 May 2023 sprint
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Playwright.py
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/src/RPA/Browser/__init__.py
  packages/main/src/RPA/Browser/common.py
  packages/main/src/RPA/FileSystem.py
  packages/main/src/RPA/Hubspot.py
  packages/main/src/RPA/JSON.py
  packages/main/src/RPA/MSGraph.py
  packages/main/src/RPA/Robocorp/WorkItems.py
  packages/main/tests/robot/test_browser.robot
  poetry.lock
  pyproject.toml
Labels: feature, enhancement

#978 Fix `RPA.JavaAccessBridge` issue with `Click Element`
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/JavaAccessBridge.py
Labels: bug

#996 Control Room: Asset Storage support through `robo`
  docs/source/contributing/development.md
  docs/source/libraries/robocorp_storage/index.rst
  docs/source/libraries/robocorp_storage/python.rst
  docs/source/releasenotes.rst
  packages/main/README.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Robocorp/Storage.py
  packages/main/src/RPA/Robocorp/WorkItems.py
  packages/main/tests/resources/secrets.yaml
  packages/main/tests/robot/test_browser.robot
  packages/main/tests/robot/test_robocorp_storage.robot
  poetry.lock
Labels: feature

#1000 `RPA.JavaAccessBridge`. add new keyword `print locator tree`
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/JavaAccessBridge.py
Labels: enhancement
