Repository robocorp/rpaframework, pull requests merged in 2023-08, with the labels that each got.

#1003 `RPA.Salesforce`. Add Salesforce OAuth2 authentication and execute_apex
  docs/source/releasenotes.rst
  packages/main/src/RPA/Salesforce.py
Labels: enhancement

#1054 `RPA.Email.ImapSmtp` Fix how email recipients are handled and improve attachment handling
  docs/source/releasenotes.rst
  packages/main/src/RPA/Email/ImapSmtp.py
Labels: bug, enhancement

#1051 Fixes in PDF, AI and documentation
  .github/workflows/pdf.yaml
  docs/source/contributing/conventions.rst
  docs/source/contributing/development.md
  docs/source/contributing/guide.rst
  docs/source/releasenotes.rst
  packages/main/README.rst
  packages/main/packages.rst
  packages/main/poetry.lock
  packages/main/src/RPA/DocumentAI/Base64AI.py
  packages/main/src/RPA/DocumentAI/DocumentAI.py
  packages/main/src/RPA/JavaAccessBridge.py
  packages/main/src/RPA/Robocorp/utils.py
  packages/main/tests/python/test_documentai.py
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/test_document.py
  packages/pdf/tests/python/test_model.py
  packages/pdf/tests/robot/test_pdf.robot
  poetry.lock
  pyproject.toml
Labels: bug

#1052 Add archive_folder_with_zip python examples
  packages/assistant/src/RPA/Assistant/library.py
  packages/main/src/RPA/Archive.py
Labels: documentation

#1058 Use common `Application` class for library COM apps
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/src/RPA/Excel/Application.py
  packages/main/src/RPA/Outlook/Application.py
  packages/main/src/RPA/Word/Application.py
  packages/main/src/RPA/application.py
  packages/main/tests/robot/test_browser.robot
  packages/main/tests/robot/test_excel_application.robot
  packages/main/tests/robot/test_outlook_application.robot
  packages/main/tests/robot/test_word_application.robot
  packages/windows/tests/robot/test_windows.robot
  poetry.lock
Labels: bug, documentation, refactor

#1064 Fix Edge in IE mode webdriver management and freezing issues
  docs/source/releasenotes.rst
  invocations/docs.py
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/webdriver.py
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/tests/robot/test_browser.robot
Labels: bug

#950 Upgrade to Robot Framework 6
  .github/workflows/assistant.yaml
  .github/workflows/aws.yaml
  .github/workflows/google.yaml
  .github/workflows/openai.yaml
  .github/workflows/recognition.yaml
  .github/workflows/windows.yaml
  docs/source/releasenotes.rst
  packages/assistant/poetry.lock
  packages/assistant/pyproject.toml
  packages/assistant/tests/results/log.html
  packages/assistant/tests/results/output.xml
  packages/assistant/tests/results/report.html
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/openai/poetry.lock
  packages/openai/pyproject.toml
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  pyproject.toml
Labels: dependency, enhancement, breaking

#1057 `RPA.Cloud.Google` Handle "application" type attachments with `MimeApplication` class
  docs/source/releasenotes.rst
  packages/google/poetry.lock
  packages/google/src/RPA/Cloud/Google/keywords/context.py
  packages/google/src/RPA/Cloud/Google/keywords/gmail.py
Labels: bug
