Repository robocorp/rpaframework, pull requests merged in 2023-02, with the labels that each got.

#795 Release 21.0.0
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Cloud/Azure.py
  poetry.lock
  pyproject.toml
Labels: feature, refactor, breaking

#682 New library `RPA.Assistant`
  docs/source/libraries/assistant/index.rst
  docs/source/libraries/assistant/python.rst
  docs/source/releasenotes.rst
  invocations/docs.py
  packages/assistant/.gitignore
  packages/assistant/LICENSE
  packages/assistant/README.rst
  packages/assistant/docs/CHANGELOG.md
  packages/assistant/docs/Migration-Guide.md
  packages/assistant/poetry.lock
  packages/assistant/pyproject.toml
  packages/assistant/src/RPA/Assistant/__init__.py
  packages/assistant/src/RPA/Assistant/flet_client.py
  packages/assistant/src/RPA/Assistant/library.py
  packages/assistant/src/RPA/Assistant/types.py
  packages/assistant/src/RPA/Assistant/utils.py
  packages/assistant/tasks.py
  packages/assistant/tests/python/__init__.py
  packages/assistant/tests/python/assistant_test.py
  packages/assistant/tests/robot/ExecutionContexts.py
  packages/assistant/tests/robot/assistant_test.robot
  poetry.lock
  pyproject.toml
Labels: feature

#805 Base64AI API support for signature matching
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/src/RPA/Desktop/keywords/screen.py
  packages/main/src/RPA/DocumentAI/Base64AI.py
  packages/main/src/RPA/DocumentAI/DocumentAI.py
  packages/main/src/RPA/Robocorp/utils.py
  packages/main/src/RPA/Tasks.py
  packages/main/tests/python/test_documentai.py
  packages/main/tests/resources/documentai/signature-check.png
  packages/main/tests/resources/documentai/signature-license.jpg
  packages/main/tests/resources/documentai/signature-recognize-response.json
  packages/main/tests/robot/test_documentai.robot
  packages/main/tests/robot/test_documentai_base64ai.robot
  poetry.lock
Labels: feature

#819 Update RPA.Assistant to 1.0.5
  poetry.lock
  pyproject.toml
Labels: dependency

#833 Bump cryptography to 39 in main
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: dependency

#834 Add some error catching to windows recorder, print in console that ESC stops recording
  packages/windows/src/RPA/Windows/main.py
Labels: bug, enhancement

#825 Allow free dialect selection
  docs/source/releasenotes.rst
  packages/main/src/RPA/Tables.py
Labels: enhancement

#839 Add `path:` strategy on windows locators
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/windows/locators.py
  packages/core/tests/python/test_windows.py
Labels: enhancement

#830 Assistant: Add support for default value inputs
  docs/source/releasenotes.rst
  packages/assistant/pyproject.toml
  packages/assistant/src/RPA/Assistant/flet_client.py
  packages/assistant/src/RPA/Assistant/library.py
  packages/assistant/tests/python/assistant_test.py
Labels: feature, enhancement

#844 Hotfix `core` path locators
  packages/core/pyproject.toml
  packages/core/src/RPA/core/webdriver.py
  packages/core/src/RPA/core/windows/locators.py
  packages/core/tests/python/test_windows.py
Labels: bug

#840 Enable `path:` strategy and tree structure walking in `RPA.Windows`
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/__init__.py
  packages/windows/src/RPA/Windows/keywords/elements.py
  packages/windows/src/RPA/Windows/keywords/locators.py
  packages/windows/src/RPA/Windows/keywords/window.py
  packages/windows/tests/robot/test_windows.robot
Labels: feature

#854 Add lang support to the `OcrLocator`
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/locators/containers.py
Labels: enhancement

#860 `RPA.PDF` Add `boxes_flow` to available conversion settings
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/model.py
Labels: enhancement

#841 Add support for OCR language parameter in RPA.Desktop image locators
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Desktop/keywords/finder.py
  packages/main/tests/resources/config/HubspotTestvars.py
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
  packages/recognition/src/RPA/recognition/ocr.py
Labels: feature
