Repository robocorp/rpaframework, pull requests merged in 2023-10, with the labels that each got.

#1105 ``rpaframework-recognition`` bump opencv-python-headless to 4.8.1 (security fix)
  docs/source/releasenotes.rst
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
Labels: bug

#1109 Inline all dev deps
  .github/workflows/assistant.yaml
  .github/workflows/aws.yaml
  .github/workflows/dialogs.yaml
  .github/workflows/docs.yaml
  .github/workflows/google.yaml
  .github/workflows/openai.yaml
  .github/workflows/pdf.yaml
  .github/workflows/recognition.yaml
  .github/workflows/windows.yaml
  packages/assistant/poetry.lock
  packages/assistant/pyproject.toml
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/dialogs/poetry.lock
  packages/dialogs/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/openai/poetry.lock
  packages/openai/pyproject.toml
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
Labels: packaging, dependency

#1110 Inline `main` and `meta` with the rest of the dev deps
  .github/workflows/main.yaml
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: dependency

#1077 Java element refresh and maximum depth support
  .gitignore
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/src/RPA/HTTP.py
  packages/main/src/RPA/JavaAccessBridge.py
  packages/main/tests/resources/test-app/BasicSwing.class
  packages/main/tests/resources/test-app/BasicSwing.jar
  packages/main/tests/resources/test-app/BasicSwing.java
  packages/main/tests/robot/test_java.robot
  poetry.lock
  pyproject.toml
Labels: enhancement

#1114 Lazily import libraries when needed
  docs/source/releasenotes.rst
  invocations/docs.py
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/ImapSmtp.py
  packages/main/src/RPA/Robocorp/WorkItems.py
  packages/main/src/RPA/SAP.py
  packages/main/src/RPA/application.py
  packages/main/tests/python/test_applications.py
  poetry.lock
Labels: enhancement

#1117 `RPA.Email.*` Add reply_to for send_message keywords
  docs/source/releasenotes.rst
  packages/main/src/RPA/Email/Exchange.py
  packages/main/src/RPA/Email/ImapSmtp.py
Labels: feature

#1116 Allow reserving multiple input Work Items
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/src/RPA/Robocorp/WorkItems.py
Labels: feature, in consideration
