Repository robocorp/rpaframework, pull requests merged in 2023-03, with the labels that each got.

#868 Hotfix `core` windows locator recording (window control)
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/windows/inspect.py
Labels: bug

#855 Windows improvements: `Print Tree`, `Set Mouse Movement`, `Set Value`
  docs/source/releasenotes.rst
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
  packages/windows/src/RPA/Windows/__init__.py
  packages/windows/src/RPA/Windows/keywords/action.py
  packages/windows/src/RPA/Windows/keywords/elements.py
  packages/windows/src/RPA/Windows/keywords/window.py
  packages/windows/src/RPA/Windows/main.py
  packages/windows/tests/robot/test_windows.robot
Labels: bug, enhancement

#870 RPA.Database : Fix psycopg2 module error
  packages/main/src/RPA/Database.py
Labels: enhancement

#875 `RPA.Database`. Remove info level logs from ``Connect To Database`` keyword
  docs/source/releasenotes.rst
  packages/main/src/RPA/Database.py
Labels: bug

#878 RPA.Outlook.application: add support for cc and bcc fields
  docs/source/releasenotes.rst
  packages/main/src/RPA/Outlook/Application.py
  packages/main/tests/robot/test_outlook_application.robot
Labels: enhancement

#859 Selenium: Correctly handle custom strategy arguments
  docs/source/releasenotes.rst
  invocations/requirements.txt
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/tests/python/test_calendar.py
  packages/main/tests/resources/locators.json
  packages/main/tests/robot/test_browser.robot
  packages/main/tests/robot/test_calendar.robot
  poetry.lock
  pyproject.toml
Labels: enhancement

#886 Align packages build system
  packages/assistant/poetry.lock
  packages/assistant/pyproject.toml
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/dialogs/poetry.lock
  packages/dialogs/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/main/pyproject.toml
  packages/openai/poetry.lock
  packages/openai/pyproject.toml
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
Labels: packaging

#889 Fix `RPA.Calendar` unit & robot tests
  packages/main/poetry.lock
  packages/main/tests/python/test_browser.py
  packages/main/tests/python/test_calendar.py
  packages/main/tests/robot/test_calendar.robot
  packages/main/tests/robot/test_files.robot
Labels: bug

#893 Fix `RPA.PDF` field setting bugs
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/test_document.py
  packages/pdf/tests/robot/test_pdf.robot
Labels: bug

#887 CodeQL warning fixes
  .github/workflows/codeql-analysis.yml
Labels: packaging

#880 Create new library `RPA.Smartsheet`
  docs/source/libraries/smartsheet/index.rst
  docs/source/libraries/smartsheet/python.rst
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Smartsheet.py
  packages/main/src/RPA/version.py
  packages/main/tests/python/smartsheet_vars.py
  packages/main/tests/python/test_smartsheet.py
  poetry.lock
Labels: feature

#908 `RPA.JavaAccessBridge`. Fix `Select Window` keyword
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/JavaAccessBridge.py
  packages/main/tests/resources/test-app/BasicSwing.class
  packages/main/tests/resources/test-app/BasicSwing.jar
  packages/main/tests/resources/test-app/BasicSwing.java
Labels: bug

#909 `RPA.PDF`. Add documentation about merge and split
  docs/source/releasenotes.rst
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/__init__.py
  packages/pdf/src/RPA/PDF/keywords/document.py
Labels: documentation

#898 Improve dev guide
  docs/source/contributing/conventions.rst
  docs/source/contributing/development.md
  docs/source/contributing/guide.rst
Labels: documentation
