Repository robocorp/rpaframework, pull requests merged in 2023-01, with the labels that each got.

#768 Bump PDF deps to latest (& migration changes)
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/__init__.py
  packages/pdf/src/RPA/PDF/keywords/document.py
  packages/pdf/src/RPA/PDF/keywords/finder.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/test_document.py
  packages/pdf/tests/python/test_finder.py
  packages/pdf/tests/python/test_model.py
  packages/pdf/tests/robot/test_pdf.robot
Labels: bug, dependency, enhancement, p-high, breaking

#770 Bump pylibcore and sphinx
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
Labels: dependency

#771 Sphinx deps upgrades in: aws, google, pdf, windows
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
Labels: dependency

#767 Release 20.0.0: Global breaking dependency updates & fixes
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/Exchange.py
  packages/main/tests/robot/test_desktop.robot
  poetry.lock
  pyproject.toml
Labels: dependency, p-high, breaking

#772 Fix docs according to latest major 20 release
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
  packages/aws/src/RPA/Cloud/AWS/__init__.py
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/google/src/RPA/Cloud/Google/keywords/document_ai.py
  packages/google/src/RPA/scripts/google_authenticate.py
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Desktop/__init__.py
  packages/main/src/RPA/Images.py
  packages/main/tests/python/test_crypto.py
Labels: documentation

#773 Dependabot cryptography upgrade
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  poetry.lock
Labels: dependency

#778 SAP. Fix order of imports
  docs/source/releasenotes.rst
  packages/main/src/RPA/SAP.py
Labels: bug

#776 Support Edge in IE mode under Selenium
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  poetry.lock
Labels: enhancement

#780 Use RPA_SELENIUM_BROWSER_ORDER env variable to determine default browsers
  docs/source/releasenotes.rst
  packages/core/pyproject.toml
  packages/core/src/RPA/core/webdriver.py
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
Labels: enhancement

#786 Fix semantic versioning break
  packages/core/pyproject.toml
  packages/core/src/RPA/core/webdriver.py
Labels: enhancement

#787 Better browser resolution with `core` 10.2.0
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  poetry.lock
Labels: enhancement

#789 Improve `RPA.PDF.Find Text` with `subtext:` strategy and `ignore_case` switch
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/finder.py
  packages/pdf/src/RPA/PDF/keywords/model.py
  packages/pdf/tests/python/__init__.py
  packages/pdf/tests/python/test_finder.py
  packages/pdf/tests/python/test_model.py
  packages/pdf/tests/resources/camelot-table.pdf
  packages/pdf/tests/robot/test_pdf.robot
Labels: feature, enhancement, breaking

#793 Improve PDF docs
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/__init__.py
  packages/pdf/src/RPA/PDF/keywords/finder.py
  packages/pdf/src/RPA/PDF/keywords/model.py
Labels: documentation

#794 Rely on `RPA.Robocorp.Vault` only (not Robocloud)
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/google/src/RPA/Cloud/Google/__init__.py
Labels: documentation, enhancement, breaking
