Repository robocorp/rpaframework, pull requests merged in 2023-09, with the labels that each got.

#1082 `RPA.Cloud.Google` New keywords for Sheets
  docs/source/releasenotes.rst
  packages/google/poetry.lock
  packages/google/pyproject.toml
  packages/google/src/RPA/Cloud/Google/keywords/sheets.py
Labels: enhancement

#1084 Make `core` use Robocorp webdriver sources and `truststore`
  docs/source/releasenotes.rst
  invocations/requirements.txt
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/__init__.py
  packages/core/src/RPA/core/certificates.py
  packages/core/src/RPA/core/webdriver.py
  packages/core/tests/python/test_webdriver.py
Labels: enhancement

#1087 `RPA.JavaAccessBridge`. fix issue with "select window by title"
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/JavaAccessBridge.py
Labels: bug

#1088 Use `core` 11.1.0 (webdriver fixes) and truststore
  config/pylint
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/robot/__main__.py
  poetry.lock
Labels: bug

#1092 `RPA.Cloud.Google`. Add possibility to send HTML email
  docs/source/releasenotes.rst
  packages/google/pyproject.toml
  packages/google/src/RPA/Cloud/Google/keywords/gmail.py
Labels: enhancement

#1090 Support for browser version retrieval
  docs/source/releasenotes.rst
  packages/core/poetry.lock
  packages/core/pyproject.toml
  packages/core/src/RPA/core/webdriver.py
  packages/core/tests/python/test_webdriver.py
Labels: feature

#1091 Selenium improvements
  docs/source/releasenotes.rst
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Browser/Selenium.py
  packages/main/tests/robot/test_browser.robot
  poetry.lock
Labels: feature

#1099 Update java-access-bridge-wrapper
  packages/main/poetry.lock
  packages/main/pyproject.toml
Labels: enhancement

#1102 `RPA.PDF` Update html to pdf keywords
  packages/pdf/poetry.lock
  packages/pdf/pyproject.toml
  packages/pdf/src/RPA/PDF/keywords/document.py
Labels: enhancement
