Repository robocorp/rpaframework, pull requests merged in 2024-04, with the labels that each got.

#1169 recognition. pillow security update
  packages/recognition/poetry.lock
  packages/recognition/pyproject.toml
Labels: dependency

#1170 openai. security update
  packages/openai/poetry.lock
  packages/openai/pyproject.toml
Labels: dependency

#1171 google. core security update
  packages/google/poetry.lock
  packages/google/pyproject.toml
Labels: dependency

#1172 windows. update core
  packages/windows/poetry.lock
  packages/windows/pyproject.toml
Labels: dependency

#1174 aws. core security update
  packages/aws/poetry.lock
  packages/aws/pyproject.toml
Labels: dependency

#1176 main. security update dependencies
  packages/main/poetry.lock
  packages/main/pyproject.toml
Labels: dependency

#1182 `RPA.Email.Exchange` Use FolderCollection to get subfolders
  packages/main/poetry.lock
  packages/main/pyproject.toml
  packages/main/src/RPA/Email/Exchange.py
Labels: bug

#1179 Update Exchange.py
  packages/main/src/RPA/Email/Exchange.py
Labels: enhancement
